# Generated by Django 6.0.3 on 2026-03-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakeCake', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Заказ принят'), ('in_delivery', 'В доставке'), ('completed', 'Завершен'), ('cancelled', 'Отменен')], default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
